"""MCP tool handlers."""

from supabase_mcp.tools.a2ui import (
    a2ui_action,
    a2ui_error,
    chat_message,
    chat_message_resource,
    data_chart_resource,
    database_overview,
    database_overview_resource,
    financial_view_resource,
    present_financial_view,
    visualize_allowed_data,
)
from supabase_mcp.tools.finance import (
    FINANCIAL_TOOLS,
    analyze_spending,
    compare_debt_scenarios,
    detect_transaction_anomalies,
    forecast_cash_balance,
    forecast_recurring_charges,
    get_accounts,
    get_bank_statements,
    get_beneficiaries,
    get_budget_progress,
    get_cash_flow,
    get_credit_cards,
    get_debt_overview,
    get_financial_alerts,
    get_financial_overview,
    get_payment_activity,
    get_savings_progress,
    get_transaction_disputes,
    get_transactions,
    get_upcoming_payments,
    predict_savings_goal,
)
from supabase_mcp.tools.schema import describe_table, list_allowed_tables
from supabase_mcp.tools.user_context import get_user_context

__all__ = [
    "FINANCIAL_TOOLS",
    "a2ui_action",
    "a2ui_error",
    "analyze_spending",
    "chat_message",
    "chat_message_resource",
    "compare_debt_scenarios",
    "data_chart_resource",
    "database_overview",
    "database_overview_resource",
    "describe_table",
    "detect_transaction_anomalies",
    "financial_view_resource",
    "forecast_cash_balance",
    "forecast_recurring_charges",
    "get_accounts",
    "get_bank_statements",
    "get_beneficiaries",
    "get_budget_progress",
    "get_cash_flow",
    "get_credit_cards",
    "get_debt_overview",
    "get_financial_alerts",
    "get_financial_overview",
    "get_payment_activity",
    "get_savings_progress",
    "get_transaction_disputes",
    "get_transactions",
    "get_upcoming_payments",
    "get_user_context",
    "list_allowed_tables",
    "predict_savings_goal",
    "present_financial_view",
    "visualize_allowed_data",
]
